name: Build MAS Release
on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: false
        default: MAS
permissions:
  contents: write
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x
      - name: Build
        shell: pwsh
        run: ./scripts/build.ps1
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: "${{ github.event.inputs.version }}-${{ github.run_number }}"
          name: "${{ github.event.inputs.version }} Build ${{ github.run_number }}"
          body_path: BUILDINFO.txt
          files: MAS-release.zip
